print("Realize seu cadastro :-]")
print("-"* 160)
n = (input("Digite seu nome: "))
print("-"* 160)
i = int(input("Digite sua idade: "))
print("-"* 160)
cpf = int(input("Digite seu [CPF]: "))
print("-"* 160)
tel = int(input("Digite seu telefone: "))
print("-"* 160)
print("Tabela de confirmaçao de Informaçoes.")
print("-"* 160)
print(f"Seu Nome: {n}")
print("-"* 160)
print(f"Sua Idade: {i}anos")
print("-"* 160)
print(f"Seu CPF: {cpf}")
print("-"* 160)
print(f"Seu Telefone: {tel}")
print("-"* 160)
print("Voce foi cadastrado com sucesso.")
print("-"* 160)
print("Seja bem vindo a Embare KRAF :-]")
print("-"* 160)
print("Agradeçemos a sua escolha!")
print("-"* 160)